from enum import StrEnum, auto

class UIKeys(StrEnum):
    """
    An Enum class that defines various UI keys used in the game.
    These keys correspond to different prompts, messages, and actions in the user interface.
    """
    NEWLINE = auto()
    CHOOSE_GAME_RULE = auto()
    CALIFORNIA_MODE = auto()
    STANDARD_MODE = auto()
    GAME_RULE_UPDATED = auto()
    CHOOSE_LOCALE = auto()
    CHOOSE_LANGUAGE_PROMPT = auto()
    FIRST_ROUND_PROMPT = auto()
    PAIR_PLUS_ROUND_PROMPT = auto()
    SECOND_ROUND_PROMPT = auto()
    ANOTHER_ROUND_PROMPT = auto()
    WELCOMING = auto()
    EXIT_PROMPT = auto()
    PRESS_ENTER_TO_EXIT = auto()
    FILE_NOT_FOUND_ERROR_PROMPT = auto()
    PLAYER_CHEATED = auto()
    PLAYER_ALREADY_CHEATED = auto()
    PLAYER_BALANCE_ALREADY_HIGH_ENOUGH = auto()
    USER_CHOICE_NOT_IN_OPTIONS_PROMPT = auto()
    INSUFFICIENT_BALANCE_PROMPT = auto()
    SHOW_PLAYER_BALANCE = auto()
    TOO_MANY_ANTE_TRIES_PROMPT = auto()
    TOO_MANY_PAIR_PLUS_TRIES_PROMPT = auto()
    MUST_TYPE_INTEGER_ERROR_PROMPT = auto()
    INT_INPUT_NOT_IN_LEGAL_RANGE_ERROR_PROMPT = auto()
    PLACE_ANTE_PROMPT = auto()
    HAS_PLACED_ANTE_PROMPT = auto()
    SKIP_PAIR_PLUS_PROMPT = auto()
    PLACE_PAIR_PLUS_PROMPT = auto()
    HAS_PLACED_PAIR_PLUS_PROMPT = auto()
    NO_PAIR_PLUS_PROMPT = auto()
    PLACE_PLAY_BET_PROMPT = auto()
    DRAW_CARD_PROMPT = auto()
    PLAYER_DREW_CARD_MESSAGE = auto()
    DEALER_DREW_CARD_MESSAGE = auto()
    SHOW_PLAYER_HAND = auto()
    SHOW_DEALER_HAND = auto()
    WIN_ANTE_BONUS_PROMPT = auto()
    WIN_PAIR_PLUS_PROMPT = auto()
    HAD_PAIR_PLUS_BET_BUT_NO_PAIR_PLUS = auto()
    FOLD = auto()
    LOSE = auto()
    DEALER_NOT_QUALIFIED = auto()
    WIN = auto()
    PUSH = auto()